apiVersion: audit.k8s.io/v1beta1
kind: Policy
rules:
  # Log all Kubernetes Event objects at Request level
  - level: Request
    resources:
    - resources: ["events"]

  # As a fallback/default, log nothing at all
  - level: None