# https://kubernetes.io/docs/tasks/kubelet-credential-provider/kubelet-credential-provider/
apiVersion: kubelet.config.k8s.io/v1alpha1
kind: CredentialProviderConfig
providers:
  - name: ecr-credential-provider
    matchImages:
      - "*.dkr.ecr.*.amazonaws.com"
    defaultCacheDuration: "3h"
    apiVersion: credentialprovider.kubelet.k8s.io/v1alpha1
