version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /ext/registry
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
    tls:
        minimumtls: tls1.2
        certificate: /var/state/apiserver.cert
        key: /var/state/apiserver.key
        clientcas:
            - /var/state/root.cert
health:
   storagedriver:
       enabled: true
       interval: 10s
       threshold: 3
